### ISSUE TITLE
Idea and planning

### ISSUE THREAD

**Issue by malhotraguy** [malhotraguy/Conuhacks2020#1]
Lets comment about the ideas on this issue

**Comment by maxtheaxe** [comment]
**Elevator Pitch and Basic Components**

- Give companies an easy way to encourage/incentivize employees to volunteer for good causes
- Recommend potential volunteer opportunities for employees looking to donate their time (or even take a break from work)
- Allow companies to visualize statistics about their employees volunteer efforts (i.e. time spent, places volunteered, percentages of employees volunteering)
- Connect volunteers and organizers via chat for all other communication (scheduling is all done systematically, but chats could be for everything else)

**Comment by adrienphilardeau** [comment]
Jobs companies might be looking for:

- Servers at soup kitchens
- Helping kids with homework
- Referee kids' games
- Helpers at animal shelters
- Volunteers at retirement homes
- Event planners

Questions:

1. Do you enjoy working with children?
2. Do you enjoy teaching and are academically inclined?
3. Do you like animals?
4. Are you a sports connoisseur (soccer, basketball, football) and in decent physical shape?
5. Would you enjoy helping the elderly carry out everyday tasks?
7. Are you very organized and enjoy coordinating events?

Tags: Server, Homework, Referee, Animals, Retirement, Planner

**Comment by adrienphilardeau** [comment]
array of tags in order = []
for(int i = 5 to 1)
      for(answers to question 1-6)
           if(score == i) then array.append(answer.tag)
