### ISSUE TITLE
Challenges Targeting

### ISSUE THREAD

**Issue by malhotraguy** [malhotraguy/Conuhacks2020#3]
Write down the sponsors challenges and write down what do you want to do in that challenge:-

**Comment by Edmund-Lui98** [comment]
**CGI's Social Responsibility Challenge**
- Will make volunteer mapping system for employees to sign up with

**Comment by Edmund-Lui98** [comment]
**Sunlife Financial: Workplace Well-Being Challenge**
- volunteer work helps with mental health of employees, improving their mental state, and overall helping prevent workplace workout

**Comment by Edmund-Lui98** [comment]
**Telus: Technology for Mental Health Well-Being**
- volunteer work helps with mental health of employees, improving their mental state, and overall helping prevent workplace workout

**Comment by Edmund-Lui98** [comment]
**GSoft: The Future of Work**
- Helps employees find and use skills outside of workplace that improves their mental state, and ultimately helping with productivity and focus

**Comment by Edmund-Lui98** [comment]
**DRW's Data Visualization Challenge**

- Allow companies to visualize statistics about their employees volunteer efforts (i.e. time spent, places volunteered, percentages of employees volunteering)

**Comment by maxtheaxe** [comment]
**Zendesk Sunshine Conversations API**

- Create communication channel for volunteers and charity contacts to organize and coordinate after being matched

**Comment by malhotraguy** [comment]
**Twilio for text messages:-**
- Text message send/receive response
