### ISSUE TITLE
Calendar Features

### ISSUE THREAD

**Issue by maxtheaxe** [malhotraguy/Conuhacks2020#4]
- [x] Sync Calendar (OAuth)
- [x] Availability (Free time overlaps)
- [x] Invites (Ability to add events/volunteer hours to each calendar)

**Comment by maxtheaxe** [comment]
Are we giving users the ability to add new calendars, or just pre-connecting the employees' and charities' calendars (during the hackathon, anyway)?

i.e. will there be a button to join on the webapp? (my vote is no, we pretend it's an enterprise connection that's built into their corporate calendar system)

**Comment by malhotraguy** [comment]
Yes agreed but for the sake of demo in hackathon we have to show that we can actually add the calendar on the fly when adding a new user. @maxtheaxe
